version: '3.8'

services:
  server:
    container_name: backend
    build:
      context: backend
      dockerfile: ./server/Dockerfile
    env_file: 
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server
    command: air cmd/main.go -b 0.0.0.0
  db: 
    image: postgres:alpine 
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
volumes:
  postgres-db: