import Menu from "@/app/components/commons/menu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <main className="h-screen flex bg-gray-50">
      <Menu></Menu>
      {children}
    </main>
  );
}